### ISSUE TITLE
Lack of Documentation for yt-dlp Dependency Requirement

### ISSUE THREAD

**Issue by Naveenravi07** [Naveenravi07/audio-scrapper#8]
Currently, the tool requires the installation of yt-dlp on the local system to function properly. However, there is no documentation available that explicitly mentions this dependency, leading to confusion and potential issues for users trying to use the tool.

**Comment by 123HelloBob** [comment]
hi! i can work on this. could you please assign it to me?

**Comment by Naveenravi07** [comment]
#9

**Comment by Naveenravi07** [comment]
The changes proposed in this pull request have been successfully merged  #9. As a result, we are closing this issue.

Thank you for your contribution!
